name: Package Cleanup

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/delete-package-versions@v3
      with: 
        package-name: 'com\.flowmastr\..+'
